### ISSUE TITLE
ritest doesn't seem give the right answer when use none zero null hypothesis

### ISSUE THREAD

**Issue by zhaoxiliang** [simonheb/ritest#10]
Please correct me if I am wrong.
I just want to replicate Imbens and Rubin(2015)'s table 5.4 with null hypothesis H0: Y1=Y0+C, C=0.5, the table should be

unit  | $Y_0$  |$Y_1$   | $W$  |$X$   |$Y$  
--|---|---|---|---|--
1  | (2.5)  | 3  |  1 |  4 |  3
2  | (4.5) |  5 |  1 |   6|  5
3  |(-0.5)  |  0 |  1 |  4 |  0
4  | 4  |  (4.5) |  0 |  4 |  4
5  | 0  |  (0.5)|  0 |  1 |  0
6  | 1  |  (1.5)|  0 |  5 |  1

in this case, Y0 = Y - W*C
but Y1 = Y + C*(1-W).
The observed statistic is still the difference in mean $\bar{Y}_t-\bar{Y}_c = (3+5+0)/3 - (4+0+1)/3=1$。but ritest report 0.5

When simulating treatment assignment, Y0, and Y1 can be seen according to the new permutate assignment variable D, so the 
the statistic will be $\sum D*Y1/\sum D - \sum (1-D)*Y0/\sum (1-D)$, p-value should be 0.7.

ritest seems to rewrite the Y <- Y - W*C to change the observed outcome into Y0, and then permute and calculate with Y0, it seems not right. 

I may understand wrong. 
```

>> . ritest d _b[d],null(y 0.5): reg y d
(running regress on estimation sample)

      Source |       SS           df       MS      Number of obs   =         6
-------------+----------------------------------   F(1, 4)         =      0.28
       Model |         1.5         1         1.5   Prob > F        =    0.6240
    Residual |  21.3333333         4  5.33333333   R-squared       =    0.0657
-------------+----------------------------------   Adj R-squared   =   -0.1679
       Total |  22.8333333         5  4.56666667   Root MSE        =    2.3094

------------------------------------------------------------------------------
           y |      Coef.   Std. Err.      t    P>|t|     [95% Conf. Interval]
-------------+----------------------------------------------------------------
           d |          1   1.885618     0.53   0.624    -4.235315    6.235315
       _cons |   1.666667   1.333333     1.25   0.279     -2.03526    5.368593
------------------------------------------------------------------------------
User specified non-zero null hypothesis
Under the null hypothesis:
 y has treatment effect: d*0.5
 (these values are being subtracted from the outcome)

Resampling replications (100)
----+--- 1 ---+--- 2 ---+--- 3 ---+--- 4 ---+--- 5 
..................................................    50
..................................................   100
Warning: 28% of the resampled realizations for _pm_1 are exactly identical to original value

      command:  regress y d
        _pm_1:  _b[d]
  res. var(s):  d
   Resampling:  Permuting d
Clust. var(s):  __000001
     Clusters:  6
Strata var(s):  none
       Strata:  1

------------------------------------------------------------------------------
T            |     T(obs)       c       n   p=c/n   SE(p) [95% Conf. Interval]
-------------+----------------------------------------------------------------
       _pm_1 |         .5      89     100  0.8900  0.0313  .8116989    .943793
------------------------------------------------------------------------------
Note: Confidence interval is with respect to p=c/n.
Note: c = #{|T| >= |T(obs)|}

```

**Comment by simonheb** [comment]
Hi,

Thanks for the detailed issue report.

First, you are right regarding what ritest does: It transforms the data by subtracting the hypothesized treatment effect and then tests if, in the transformed data, the treatment effect is 0. I.e., it only focuses on what you call y_0. In this y_0, the "remaining" treatment effect is 0.5, which is that the output reports as "T(obs)", and which is the value against which the distribution of statistics from the permutations gets compared. 

Can you elaborate on what other procedure you are suggesting?

**Comment by zhaoxiliang** [comment]
Hi Simonheb,
 
Thanks for your quick response. Got it.  Could you explain why p-value is 0.9? I find the conventional difference in mean statistics for the 20 possible permutations are:
1   0.0000000       
2  -3.0000000      
3  -0.3333333      
4  -1.0000000       
5   0.3333333       
6   3.0000000       
7   2.3333333       
8   0.0000000     
9  -0.6666667       
10  2.0000000       
11 -1.0000000       
12  1.6666667       
13  1.0000000       
14 -1.3333333    
15 -2.0000000       
16  0.6666667       
17  2.0000000       
18  1.3333333      
19  4.0000000       
20  1.0000000   

There are 14 larger or equal 1, and 16 larger or equal 0.5, the p-value is 14/20=0.7 or 16/20=0.8, why 0.9? Thanks a lot.

**Comment by simonheb** [comment]
What happens if you increase the number of repetitions?

**Comment by zhaoxiliang** [comment]
increase the number of repetitions should not change much.

There are 9 cases which is on the right of the observed statistic value 1, which results in the right one side p-value 9/20=0.45, if you assume the distribution is symmetric, and double the right one side p-value, it will give you a p-value of 0.9. In this example, it's left one side p-value (statistic <= -1) is 5/20=0.25, the distribution is not symmetric.

I wonder whether you handle the two-side p-value like this, double the probability P(statistic> statistic observed) assuming the distribution is symmetric?

**Comment by simonheb** [comment]
Increasing the number of repetitions does matter because with few repetitions your p-value will depend on the random draw of assignments. This will average out if you increase the number of observations. An alternative would be to compute the exact p-value directly, which is what you do here manually. This can also be done with ritest, but requires some coding. You can find an example for that in the Stata journal article I wrote for ritest.

Regarding your question. For two-sided tests, I compute the p-value as "c = #{|T| >= |T(obs)|}" (see the output you posted above). You can however also tell ritest to report a left-sided or right-sided test (its explained in the help-file).

Let me know if there's anything else that is unclear

**Comment by zhaoxiliang** [comment]
Sure, thanks

**Comment by zhaoxiliang** [comment]
sorry to bother again.

I repeat 10000 times, ritest still gives .9

      Command: regress y d
        _pm_1: _b[d]
  res. var(s):  d
   Resampling:  Permuting d
Clust. var(s):  __000001
     Clusters:  6
Strata var(s):  none
       Strata:  1

------------------------------------------------------------------------------
T            |     T(obs)       c       n   p=c/n   SE(p) [95% Conf. Interval]
-------------+----------------------------------------------------------------
       _pm_1 |         .5    9035   10000  0.9035  0.0030  .8975446   .9092192
------------------------------------------------------------------------------
Note: Confidence interval is with respect to p=c/n.
Note: c = #{|T| >= |T(obs)|}


You said in the first comment, the permutation is on the transformed data or $Y_0$ what I called, which will result in the statistic values are just the listed value I post above minus 0.5, which will be

1 | -0.5000000
2 | -3.5000000
3 | -0.8333333
4 | -1.5000000
5 | -0.1666667
6 | 2.5000000
7 | 1.8333333
8 | -0.5000000
9 | -1.1666667
10 | 1.5000000
11 | -1.5000000
12 | 1.1666667
13 | 0.5000000
14 | -1.8333333
15 | -2.5000000
16 | 0.1666667
17 | 1.5000000
18 | 0.8333333
19 | 3.5000000
20 | 0.5000000

if you count #{|T| >=0.5}, there are 18, resulting p 18/20=0.9.

I wonder this is about the test statistics, can we still use the usual difference in mean as test statistics, at the null hypothesis $Y_1=Y_0+0.5$, we can recover the missing value, when randomize treatment assignment, we can see the hypothetical $Y_1$ for those who randomized into treatment, and $Y_0$ into control. The new test statistics should depend on the new simulated $Y_1$ and $Y_0$.

In your first comment, you say ritest permutate on the transformed data Y-d*0.5, which result the test statistics value less than the usual difference in mean statistic by 0.5, then we will get a different p-value.

**Comment by simonheb** [comment]
Hey, sorry for taking so long to respond.

Certainly there are multiple ways to conduct such a test, which will all either be numerically equivalent, or be different and this have power against different alternative hypothesis.

In principle other variants of the tests can also be implemented using ritest. However, I do not quite understand the test you are suggesting. If you're interested in discussing this, please describe step by step how you'd want the rest to use y0 and y1, and I'll be happy to brainstorm with you.
