### ISSUE TITLE
Reject option

### ISSUE THREAD

**Issue by jeandigitale** [simonheb/ritest#2]
Hi Simon - is it possible to get a reject option like there is in permute? I have a few models in my permutation that aren't converging, and would like to reject those: e.g. reject(e(converged)!=1) using Stata's permute command.

The clustering option in ritest is exactly what I need, so I would very much like to be able to use your package.

Thanks!

**Comment by simonheb** [comment]
I hadn't thought about this. My initial thought is that this is a somewhat weird restriction on the permutation. Then again, there are certainly cases that I'm missing, in which this could be desirable behavior.

This isn't super difficult to implement, I'm just a bit busy with other things at the moment. I will try to do this next month and will post here once I'm done

**Comment by jeandigitale** [comment]
Thanks so much!

**Comment by simonheb** [comment]
Hey, just quickly ported the code lines for `reject()` from the `permute.ado`, i think it might already work. Would you mind beta-testing it and check if everything works as expected?

[ritest.zip](https://github.com/simonheb/ritest/files/3667332/ritest.zip)

**Comment by jeandigitale** [comment]
It works! Thanks so much for adding this - this is so helpful to me.

Best,
Jean
