### ISSUE TITLE
Problem with sampling source file path with internal spaces

### ISSUE THREAD

**Issue by robbiediv** [simonheb/ritest#4]
Simon,

Thanks for this useful command! I just wanted to let you know about a small issue. When using an external sampling file (with the samplingsourcefile option), ritest throws an error if the path to the file contains internal spaces. Almost all my collaborators name files/directories with internal spaces, so this causes a bit of a headache for me. I believe this is an easy fix--all that's needed is to add some quotation marks around the file.

Best,
Robbie

**Comment by simonheb** [comment]
Hey, Robbie, sorry that replying took so long.

This in sounds indeed like an easy fix  as you describe it. Unfortunately I am not able to replicate the issue. Can you tell me which version of ritest you are using (type `which ritest` in Stata) and, if possible also send me the line of code (with the spaces) that causes the error?

Edit: I just realized that this might also be OS-specific, so I rewrote some minor bits of the code to be more robust regarding filenames. Please see if updating to the latest version helps. If not, please re-open this issue

**Comment by robbiediv** [comment]
Simon,

Thanks for your response. Unfortunately, after updating ritest to version 1.1.5, I still encounter the same issue. For example, the following command:

`ritest treated_sep18 _b[treated_sep18], reps(1000) samplingsourcefile("resample1000_phase copy.dta") samplingmatchvar(namakabupaten): quietly areg total_subsidy treated_sep18, absorb(finalstratum) vce(cluster KABU)`

throws this error: 

> Failed while calling resampling procedure. Call was: 
{stata permute_extfile, run(1) resampvar(treated_sep18) file(`
resample1000_phase not found

However, I know that `"resample1000_phase copy.dta"` is a valid Stata file name, because for example, I can call `u "resample1000_phase copy.dta"` without issue.

Just FYI, I use MacOS 10.14.6 and Stata/SE 16.0.

**Comment by simonheb** [comment]
Yeah, that really looks like the fuck-up is on my side. I'll fix it.

**Comment by simonheb** [comment]
I uploaded a version 1.1.6 to github. Can you check if this solves your problem now? If not, please re-open this issue.

Thanks for your feedback and patience.

**Comment by robbiediv** [comment]
It works now. Thanks Simon!
