### ISSUE TITLE
Tie treatment variables together in permutation

### ISSUE THREAD

**Issue by aphipps6** [simonheb/ritest#6]
Hi Simon,

I hope you're doing well, and I appreciate all the work that's gone into this. 

I have three different treatment variables that are all continuous. However, the treatments are not independent from each other (though they are not perfectly colinear). I'm trying to figure out how I can permute observations while keeping these treatment variables "tied" together. For example, suppose I have the following data:

ID        treat1        treat2        treat3        controlvar
1             1                1               1                   A
2             2                2               2                   B
3             3                3               3                   C

If I permute over treat1, the relationship with treat2 and treat3 is broken and I end up with stuff like

ID        treat1        treat2        treat3        controlvar
1             3                1               1                   A
2             1                2               2                   B
3             2                3               3                   C

But I want to have something like this:

ID        treat1        treat2        treat3        controlvar
1             2                2               2                   A
2             3                3               3                   B
3             1                1               1                   C

I'm still interested mainly in the coefficient of treat1, so I don't need to test treat1, treat2, and treat3 simultaneously.

I imagine there's a way to use programmatic re-sampling to accomplish this, but I haven't been able to make it work. It's also possible I've missed something obvious. It seems like a convenient option would be to keep treatment combinations, or a FAQ explanation of how this could be done.

Thank you very much!

**Comment by simonheb** [comment]
Hi,

If I understand you correctly, you basically want to always keep the relationship of these three variables as is. There's no obvious short-hand for this (and I believe this a rather atypical case). There are many different possible approaches, but since you don't seem to have clusters/strata, I guess the easiest way would be to simply write your own small routine:
```
program permute_three_treatments_together
		syntax , * //ignore all options that may be passed to the program
		tempvar random oldposition newtreat1 newtreat2 newtreat3
                gen `oldposition' = _n

                //shuffle observations ...
                gen `random' = rnormal()
                sort  `random', stable 
	        //... while keeping treatment as is
         	replace `newtreat1' = treat1[`oldposition'] 
         	replace `newtreat2' = treat2[`oldposition'] 
         	replace `newtreat3' = treat3[`oldposition']
                replace treat1 = `newtreat1' 
                replace treat2 = `newtreat2' 
                replace treat3 = `newtreat3' 
end
ritest treat1 _b [treat1], samplingprogram(permute_three_treatments_together) samplingprogramoptions ("") : /// 
regress `var' treat1 treat2 treat3 controls 
```
This code is not tested and you might need to debug it a little. You also might be able to come up with a version that is slightly more performant. If you still code to actually replicate the original (i.e., true) treatment assignment procedure, you should paste that into the `permute_three_treatments_together`.

Let me know whether this works for you.

**Comment by aphipps6** [comment]
Thank you very much! I'll test it and get back. I have never written custom stata programs and I wasn't sure how it would plug in with ritest.
