### ISSUE TITLE
ritest with ivreg

### ISSUE THREAD

**Issue by pattiritter** [simonheb/ritest#7]
Dear Simon,
I am using ritest, and I love it! and I was wondering if you could help me with this question. I am analyzing an experiment and using ritest to get the pval of the Intention to Treat estimates, but I also want to use it to get the pval of the second stage estimates (i.e using the treatment as an instrument). The pvals from ritest and OLS are very similar in the case of the ITT estimates but completelt different for the ivreg/second stage estimates. Does ritest work well with ivreg?
I also find this code, and here the same thing happens with the pval. And in this case, by construction the pval should be small, right?
https://gist.github.com/bbdaniels/0222185fe0a1d084e627ab79aaf1065a?short_path=ce94f81
thanks!!

**Comment by simonheb** [comment]
Hey @pattiritter, I already replied to your comment on the World Bank Impact Blog (https://blogs.worldbank.org/impactevaluations/finally-way-do-easy-randomization-inference-stata). So I'm only pasting my answer here for completeness.

> Hi Patti, I'm the author of ritest and David was so kind to notify me about your question. Technically, ritest works fine with ivreg etc. Meaning: it is able to compare sample realizations of a certain statistic against the distribution of this under permuted treatment. Econometrically however, it is not obvious that this provides a test for what you intend to test. At the risk of oversimplifying things, this is what happens: by resampling treatment in a normal OLS/reduced form/ITT, you're imposing the null that treatment does not matter, which is usually the null that you want to test. Contrarily, in the IV context, resampling the instrument imposes the null that the instrument is entirely irrelevant (and exogenous), which is usually not what you want test. So you don't really learn much from a rejection here. I.e., may not be asking/answering the same question as you would with the standard IV p-value. I've seen people refer this paper and presentation by Paul Rosenbaum and Guido Imbens in the context of randomization and instrumental variables (http://www-stat.wharton.upenn.edu/~rosenbap/ivTalk.pdf, https://scholar.harvard.edu/files/imbens/files/randomization_inference_…), which seems to contain all building blocks of a simple, but more useful test. In spite of its simplicity and benefits, I have neither seen applied researchers use this regularly nor have I worked with this myself. I only recently started looking at this, but I find this interesting, so if anyone here is interested in working on this (or knows someone who is), please reach out!
