### ISSUE TITLE
save output from ritest

### ISSUE THREAD

**Issue by nicholas-weller** [simonheb/ritest#8]
Hi,

I am doing separate analyses for a number of different time periods and then I would like to create a plot that displays the p-values from ritest for each of the separate analyses. I've been able to do this usually using coefplot in STATA, but I cannot seem to store the computed p-value after using ritest. 

------------------------------------------------------------------------------
T            |     T(obs)       c       n   p=c/n   SE(p) [95% Conf. Interval]
-------------+----------------------------------------------------------------
       _pm_1 |   39.23121      16    1000  0.0160  0.0040  .0091723   .0258532
------------------------------------------------------------------------------
 
Is it possible to save the "p=c/n" from ritest?

Currently, I have tried code like this:
eststo cong105RI:ritest T105 _b[T105], reps(1000) seed(125): reg hrc T105 nominate_d1  Demvoteshare  if congress==105 & district>0 &cem_matched==1
estimate store cong105RI

However, this doesn't store the ritest output. it stores the primary out from the "reg" command. 

any help is much appreciated!

thanks, nick

**Comment by simonheb** [comment]
Hey Nick.

Maybe check out this: https://github.com/simonheb/ritest#esttab

If it doesn't help, let me know.

**Comment by nicholas-weller** [comment]
Thanks. Not sure how I missed that when I was looking at the documentation for RItest.
