### ISSUE TITLE
What is the estimation result that is displayed after ritest?

### ISSUE THREAD

**Issue by NilsEnevoldsen** [simonheb/ritest#9]
What is the estimation that is displayed after ritest? I thought it was identical to the estimation specified by *command*, but in the following example it appears to be different.

Note that this estimation looks misspecified, but I still didn't expect the result to change.

Replication:

```stata
clear
input byte(y x)
  0 1
  0 1
  0 2
  1 2
  0 3
  2 3
end

tobit y i.x, ll vce(r)
ritest x _b[2.x] _b[3.x], reps(10) seed(123): `e(cmdline)'
```

Result:

```stata
. tobit y i.x, ll vce(r)

Refining starting values:

Grid node 0:   log likelihood = -8.1684125

Fitting full model:

Iteration 0:   log pseudolikelihood = -8.1684125  
Iteration 1:   log pseudolikelihood = -5.6567519  
Iteration 2:   log pseudolikelihood =  -5.103786  
Iteration 3:   log pseudolikelihood = -5.0520918  
Iteration 4:   log pseudolikelihood = -5.0505978  
Iteration 5:   log pseudolikelihood =  -5.050478  
Iteration 6:   log pseudolikelihood = -5.0504713  
Iteration 7:   log pseudolikelihood = -5.0504701  
Iteration 8:   log pseudolikelihood = -5.0504699  

Tobit regression                                    Number of obs     =      6
                                                           Uncensored =      2
Limits: Lower =    0                                    Left-censored =      4
        Upper = +inf                                   Right-censored =      0

                                                    F(2, 4)           =   5.72
                                                    Prob > F          = 0.0670
Log pseudolikelihood = -5.0504699                   Pseudo R2         = 0.1975

------------------------------------------------------------------------------
             |               Robust
           y | Coefficient  std. err.      t    P>|t|     [95% conf. interval]
-------------+----------------------------------------------------------------
           x |
          2  |    7.71567   2.669239     2.89   0.045     .3046747    15.12667
          3  |   8.315285   2.475379     3.36   0.028     1.442532    15.18804
             |
       _cons |  -7.798641   3.509734    -2.22   0.090    -17.54323    1.945944
-------------+----------------------------------------------------------------
     var(e.y)|   2.025009   1.882417                      .1532986    26.74949
------------------------------------------------------------------------------

. ritest x _b[2.x] _b[3.x], reps(10) seed(123): `e(cmdline)'
(running tobit on estimation sample)

Tobit regression                                   Number of obs     =       6
                                                          Uncensored =       2
Limits: Lower =    0                                   Left-censored =       4
        Upper = +inf                                  Right-censored =       0

                                                   F(2, 8)           = 1220.01
                                                   Prob > F          =  0.0000
Log pseudolikelihood = -5.0504699                  Pseudo R2         =  0.1975

------------------------------------------------------------------------------
             |               Robust
           y | Coefficient  std. err.      t    P>|t|     [95% conf. interval]
-------------+----------------------------------------------------------------
           x |
          2  |   8.657274   .1775003    48.77   0.000     8.247958     9.06659
          3  |   9.256917   .2248567    41.17   0.000     8.738397    9.775438
             |
       _cons |  -8.740327    .263799   -33.13   0.000    -9.348648   -8.132005
-------------+----------------------------------------------------------------
      /sigma |   1.423002   .1274918                      1.129006    1.716999
------------------------------------------------------------------------------

Resampling replications (10)
----+--- 1 ---+--- 2 ---+--- 3 ---+--- 4 ---+--- 5 
..........
Warning: 50% of the resampled realizations for _pm_1 are exactly identical to original value
Warning: 50% of the resampled realizations for _pm_2 are exactly identical to original value

      Command: tobit y i.x, ll vce(r)
        _pm_1: _b[2.x]
        _pm_2: _b[3.x]
  res. var(s):  x
   Resampling:  Permuting x
Clust. var(s):  __000001
     Clusters:  6
Strata var(s):  none
       Strata:  1

------------------------------------------------------------------------------
T            |     T(obs)       c       n   p=c/n   SE(p) [95% Conf. Interval]
-------------+----------------------------------------------------------------
       _pm_1 |   8.657274       7      10  0.7000  0.1449  .3475471   .9332605
       _pm_2 |   9.256917       5      10  0.5000  0.1581   .187086    .812914
------------------------------------------------------------------------------
Note: Confidence intervals are with respect to p=c/n.
Note: c = #{|T| >= |T(obs)|}
```

**Comment by simonheb** [comment]
I'm not on a computer right now but will check this tomorrow. I find the result you get as unexpected as you do. To speed this up, what is the output you get when you type:
```
clear
input byte(y x)
  0 1
  0 1
  0 2
  1 2
  0 3
  2 3
end

tobit y i.x, ll vce(r)
`e(cmdline)'
`e(cmdline)'
`e(cmdline)'
```

**Comment by simonheb** [comment]
Ok, I figured it out. It is the ouput of your command. But since ritest was written on Stata 13, it executes your command as if it was Stata 13. Tobit changed the way the command works recently and this then causes the problem you see here.

The "version 13" thing is to ensure backwards compatibility. However, it seems this is clearly undesired behavior in your case. I see two options:

1. I change ritest to be for Stata 17, which will make it unusable for all users of older versions
2. You add `version 13` to the beginning of your do file.

I'd prefer an option that will prevent future users from running into that problem (i.e., 1). But I also don't want to exclude users of old versions just to solve that issue. I'll think about this for a while. Let me know if you have thoughts. (you can of course also just download the ritest ado and replace the `version 13` with `version 15.1` on your PC locally. That should solve your problem.

**Comment by simonheb** [comment]
I updated ritest to use the stata 17 interpreter. To install the new version of ritest type:

    net describe ritest, from(https://raw.githubusercontent.com/simonheb/ritest/master/)

And install it from there.

Let me know if this fixes your problem and if anything unexpected happens.

**Comment by NilsEnevoldsen** [comment]
Thanks for the very prompt investigation, Simon. I'm not sure what the best resolution is. Cutting off old versions is a steep cost. For my own purposes, using a modified ado file will probably work. I wonder how similar programs handle this scenario. I suppose you could assert a minimum `c(version) >= foo` without actually specifying `version foo`, but that opens up some problems of its own.

**Comment by NilsEnevoldsen** [comment]
I'm getting `you must specify one of means, proportions, or variances following cii` with the new version. Checking `help ci_14_0` shows that there were syntax changes to this command.

**Comment by simonheb** [comment]
I see. Sorry for that. I'll investigate further.

**Comment by simonheb** [comment]
In the meantime, you could work with suggestion 2 ("version 13" in your code). Provided that whatever `tobit` spits out in that case can be useful to you. Haven't worked with `tobit`. But I guess it's just a differently version of the same estimates?

**Comment by NilsEnevoldsen** [comment]
I went the other direction and am using a local fork with `version 17` and `cii proportions …`. (That is the appropriate `cii` subcommand, correct?)

**Comment by simonheb** [comment]
Sounds very good. Let me know if you find other issues with using version 17.

Proportions sounds right as this is the ci for the p value, which is a proportion. Alternatively you could replace the ci line with this

     version 13: ci tv_hours, level(99)

Which would allow you to use the old syntax.
